language: node_js
node_js:
  - 14.8.0

cache:
  npm: true
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

deploy:
  provider: firebase
  token:
    secure: $FIRE_TOK
  skip_cleanup: true
  local_dir: build
  on:
    branch: main
