language: node_js
node_js:
  - 14.8.0

cache:
  npm: true
  directories:
    - node_modules

install:
  - npm install
  - npm install firebase-tools -g

script:
  - npm run build
  - firebase deploy --only-hosting --token "$FIRE_TOK"
# deploy:
#   provider: pages
#   skip_cleanup: true
#   github-token: $GIT_TOK
#   local_dir: build
#   on:
#     branch: main
